language: python

services:
  - docker

install:
  - pip install requests    
before_script:
  - docker-compose up -d

script: pytest tester.py -s

env:
  global:
    - IMAGE_NAME=bnaich-server

after-success:
  - test $TRAVIS_BRANCH = "master"  &&
         echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
         docker build --tag ${DOCKER_USERNAME}/pracmin_server . &&
         docker push ${DOCKER_USERNAME}/pracmin_server
        

