language: python

services:
  - docker

install:
  - pip install requests    
before_script:
  - docker-compose up -d

script: pytest tester.py -s

after-success:
        IMAGE_NAME=bnaich-server
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
        docker tag "${DOCKER_USERNAME}/${IMAGE_NAME}" . &&
        docker push ${DOCKER_USERNAME}/${IMAGE_NAME}
        

